from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def generate_report(data, filename="TruthLens_Report.pdf"):

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    body = styles["BodyText"]

    doc = SimpleDocTemplate(filename)

    story = []

    # ----------------------------------------
    # Header
    # ----------------------------------------

    story.append(
        Paragraph("TruthLens AI", title)
    )

    story.append(
        Paragraph("Enterprise Fraud Investigation Report", heading)
    )

    story.append(Spacer(1, 20))

    applicant = data.get("applicant", {})
    fraud = data.get("fraud", {})
    documents = data.get("documents", [])

    # ----------------------------------------
    # Applicant Information
    # ----------------------------------------

    story.append(
        Paragraph("Applicant Information", heading)
    )

    applicant_table = [["Field", "Value"]]

    for key, value in applicant.items():
        applicant_table.append([key.title(), str(value)])

    table = Table(applicant_table, colWidths=[170, 320])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # ----------------------------------------
    # Uploaded Documents
    # ----------------------------------------

    story.append(
        Paragraph("Uploaded Documents", heading)
    )

    for doc_data in documents:

        story.append(
            Paragraph(
                f"• {doc_data['documentType']} ({doc_data['filename']})",
                body,
            )
        )

    story.append(Spacer(1, 20))

    # ----------------------------------------
    # Fraud Summary
    # ----------------------------------------

    story.append(
        Paragraph("Fraud Assessment", heading)
    )

    summary = [

        ["Fraud Score", f"{fraud.get('fraudScore',0)}%"],

        ["Risk Level", fraud.get("risk", "-")],

        ["Analysis Confidence", f"{fraud.get('aiConfidence',0)}%"],

    ]

    summary_table = Table(summary, colWidths=[220, 220])

    summary_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("BACKGROUND", (0, 0), (-1, -1), colors.beige),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(summary_table)

    story.append(Spacer(1, 20))

    # ----------------------------------------
    # Recommendation
    # ----------------------------------------

    score = fraud.get("fraudScore", 0)

    if score >= 75:
        recommendation = "REJECT"

    elif score >= 40:
        recommendation = "MANUAL REVIEW"

    else:
        recommendation = "APPROVE"

    story.append(
        Paragraph(
            f"<b>Final Recommendation: {recommendation}</b>",
            heading,
        )
    )

    story.append(Spacer(1, 20))

    # ----------------------------------------
    # AI Findings
    # ----------------------------------------

    story.append(
        Paragraph("AI Findings", heading)
    )

    findings = fraud.get("findings", [])

    if findings:

        for finding in findings:

            story.append(
                Paragraph(
                    f"• <b>{finding['title']}</b><br/>{finding['description']}",
                    body,
                )
            )

    else:

        story.append(
            Paragraph(
                "No major inconsistencies detected.",
                body,
            )
        )

    story.append(Spacer(1, 20))

    # ----------------------------------------
    # Footer
    # ----------------------------------------

    story.append(
        Paragraph(
            f"Generated on {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            body,
        )
    )

    story.append(
        Paragraph(
            "<b>Generated by TruthLens AI Enterprise</b>",
            heading,
        )
    )

    doc.build(story)

    return filename