import { Terminal, CircleDot } from "lucide-react";

export default function LiveInvestigationLog({ logs }) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6">

      <div className="flex items-center gap-3">

        <Terminal className="h-6 w-6 text-sky-400" />

        <h2 className="text-xl font-bold text-white">
          Live Investigation Log
        </h2>

      </div>

      <p className="mt-2 text-sm text-slate-400">
        Real-time events generated by the TruthLens AI Enterprise pipeline.
      </p>

      <div className="mt-6 h-[420px] overflow-y-auto rounded-2xl border border-slate-800 bg-slate-950 p-4">

        {logs.map((log, index) => (

          <div
            key={index}
            className="mb-4 flex items-start gap-3"
          >

            <CircleDot className="mt-1 h-4 w-4 text-emerald-400" />

            <div>

              <p className="text-xs text-slate-500">
                {log.time}
              </p>

              <p className="text-sm text-white">
                {log.message}
              </p>

            </div>

          </div>

        ))}

      </div>

      <div className="mt-5 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4">

        <p className="text-sm text-emerald-300">
          System Status
        </p>

        <p className="mt-1 text-lg font-semibold text-white">
          Investigation Running Normally
        </p>

      </div>

    </div>
  );
}